# Global Config
StylesPath = .vale
MinAlertLevel = error

Vocab = Authentication

IgnoredScopes = text.frontmatter.page_type, text.frontmatter.category, text.frontmatter.recipe, text.frontmatter.id, code
IgnoredClasses = inline-code

[*.{md,mdx}]
BasedOnStyles = SuperTokens, SuperTokensErrors

[*.tsx]
BasedOnStyles = SuperTokensErrors

[docs/references/backend-sdks/supertokens-nodejs/*.{md,mdx}]
BasedOnStyles = SuperTokensErrors

[docs/references/frontend-sdks/supertokens-auth-react/*.{md,mdx}]
BasedOnStyles = SuperTokensErrors

[docs/references/frontend-sdks/supertokens-web-js/*.{md,mdx}]
BasedOnStyles = SuperTokensErrors

[docs/references/plugins/*.{md,mdx}]
BasedOnStyles = SuperTokensErrors
