#!/bin/bash

echo "-----------Building documentation pages-----------\n"
RED='\033[0;31m'
NC='\033[0m' # No color
YELLOW='\033[33m'
GREEN='\033[32m'
currentDir=$(pwd)

target="docs_server"
while getopts ":hg" opt; do
    case ${opt} in
    h)
        echo "Usage:"
        echo "To build for local docs server run ./buildAllDocs"
        echo "To build for main website run ./buildAllDocs -g"
        exit 0
        ;;
    g)
        target="supertokens_backend"
        ;;
    \?)
        echo "Invalid Option: -$OPTARG" 1>&2
        echo "Usage:"
        echo "To build for local docs server run ./buildAllDocs"
        echo "To build for main website run ./buildAllDocs -g"
        exit 1
        ;;
    esac
done
shift $((OPTIND - 1))

for d in *; do
    if [ -d "$d" ]; then
        dirName=$(basename $d)
        if [ $dirName == "static" ] || [ $dirName == "docs_dev_server" ] || [ $dirName == "v2" ]; then
            continue
        fi

        if [ "$target" = "docs_server" ]; then
            ./buildDocs $dirName
        fi

        if [ "$target" = "supertokens_backend" ]; then
            ./buildDocs -g $dirName
        fi
    fi
done

if [ "$target" = "docs_server" ]; then
    ./buildDocs
fi

if [ "$target" = "supertokens_backend" ]; then
    ./buildDocs -g
fi

# we must execute buildDocsForProduction inside the v2 folder only.
(cd ./v2 && npm run build)