import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)
const sidebars: SidebarsConfig = {
  docs: [
    { type: "doc", id: "index" },
    {
      type: "category",
      label: "Quickstart",
      customProps: { isMainCategory: true },
      items: [
        {
          type: "autogenerated",
          dirName: "quickstart",
        },
      ],
    },
    {
      type: "category",
      label: "Authentication",
      customProps: { isMainCategory: true },
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "authentication",
        },
      ],
    },
    {
      type: "category",
      label: "Additional Verification",
      customProps: { isMainCategory: true },
      items: [{ type: "autogenerated", dirName: "additional-verification" }],
    },
    {
      type: "category",
      label: "Post Authentication",
      customProps: { isMainCategory: true },
      items: [{ type: "autogenerated", dirName: "post-authentication" }],
    },
    {
      type: "category",
      label: "Migration",
      customProps: { isMainCategory: true },
      items: [{ type: "autogenerated", dirName: "migration" }],
    },
    {
      type: "category",
      label: "Platform Configuration",
      customProps: { isMainCategory: true },
      items: [{ type: "autogenerated", dirName: "platform-configuration" }],
    },
    {
      type: "category",
      label: "Deployment",
      customProps: { isMainCategory: true },
      items: [{ type: "autogenerated", dirName: "deployment" }],
    },
  ],
  references: [{ type: "autogenerated", dirName: "references" }],
};

export default sidebars;
