#!/bin/bash

RED='\033[0;31m'
NC='\033[0m' # No color
YELLOW='\033[33m'
GREEN='\033[32m'

echo -e "${YELLOW}Checking for uncommitted files${NC}"

numberOfUncommitedFiles=`git ls-files . --exclude-standard --deleted --modified --others -m | wc -l`

if [ $numberOfUncommitedFiles -ne 0 ]
then
    echo -e "${YELLOW}Please stash or commit all unstaged/uncommitted files, exiting${NC}"
    exit 1
fi

echo -e "${YELLOW}Running dry run build${NC}"

DRY_RUN=true MODE=production npx docusaurus build

if [[ $? -ne 0 ]] 
then
    echo -e "${RED}Dry run build failed, exiting, resetting git index${NC}"
    git add --all
    git reset --hard
    exit 1
fi

echo -e "${YELLOW}Changes during dry run${NC}"
git --no-pager diff

echo -e "${GREEN}Dry run build succeeded, resetting git index${NC}"
git add --all
git reset --hard