#!/bin/bash

RED='\033[0;31m'
NC='\033[0m' # No color
YELLOW='\033[33m'
GREEN='\033[32m'

echo -e "\n${YELLOW}******** Checking for uncommitted files ********${NC}\n"

numberOfUncommitedFiles=`git ls-files . --exclude-standard --deleted --modified --others -m | wc -l`

if [ $numberOfUncommitedFiles -ne 0 ]
then
    echo -e "\n${YELLOW}******** Please stash or commit all unstaged/uncommitted files, exiting ********${NC}\n"
    exit 1
fi

echo -e "\n${YELLOW}******** Running dry run build ********${NC}\n"

DRY_RUN=true MODE=production npx docusaurus build

if [[ $? -ne 0 ]] 
then
    echo -e "\n${RED}******** Dry run build failed, exiting, resetting git index ********${NC}\n"
    git add --all
    git reset --hard
    exit 1
fi

echo -e "\n${YELLOW}******** Changes during dry run ********${NC}\n"
git --no-pager diff

echo -e "\n${YELLOW}******** Dry run build succeeded, resetting git index ********${NC}\n"
git add --all
git reset --hard