#!/bin/bash

RED='\033[0;31m'
NC='\033[0m' # No color
YELLOW='\033[33m'
GREEN='\033[32m'

ignore_error="$1"

# Clear docusaurus cache before building
npx docusaurus clear .

if [[ $ignore_error != "true" ]]
then
    MODE=production npx docusaurus build
    if [[ $? -ne 0 ]]
    then
        echo "build failed... exiting!"
        exit 1
    fi
else
    MODE=production CODE_TYPE_CHECK=nothing npx docusaurus build
fi

echo "Copying to supertokens-backend-website..."

# remove unnecessary files
rm ./build/index.html
rm ./build/blog.html
rm ./build/404.html
rm ./build/.nojekyll

# replaces all the occurances of supertokens.com/ with supertokens.com/docs when it's not starting with supertokens.com/img.
sed -i '' '/supertokens\.com\/img/!s/supertokens\.com/supertokens.com\/docs/g' ./build/opensearch.xml

mv ./build/opensearch.xml ./build/docs

# copy build folder to proper location
# Check if folder exists
if [ ! -d ../../supertokens-backend-website/app/docs/v2 ]; then
    # folder does not exist, probably a new docs project and the folder hasnt been created before running this
    echo -e "${YELLOW}creating directory supertokens-backend-website/app/docs/v2 since it does not exist${NC}"
    mkdir ../../supertokens-backend-website/app/docs/v2
fi
# remove current content
rm -rf ../../supertokens-backend-website/app/docs/v2/*
# copy everything inside the build directory
cp -r ./build/* ../../supertokens-backend-website/app/docs/v2/

echo "Done!"