#!/bin/bash

RED='\033[0;31m'
NC='\033[0m' # No color
YELLOW='\033[33m'
GREEN='\033[32m'

npx docusaurus build

# remove unnecessary files
rm ./build/sitemap.xml
rm ./build/index.html
rm ./build/404.html
rm ./build/opensearch.xml
rm ./build/.nojekyll

# copy build folder to proper location
# Check if folder exists
if [ ! -d ../../supertokens-backend-website/app/docs/v2 ]; then
    # folder does not exist, probably a new docs project and the folder hasnt been created before running this
    echo -e "${YELLOW}creating directory supertokens-backend-website/app/docs/v2 since it does not exist${NC}"
    mkdir ../../supertokens-backend-website/app/docs/v2
fi
# remove current content
rm -rf ../../supertokens-backend-website/app/docs/v2/*
# copy everything inside the build directory
cp -r ./build/* ../../supertokens-backend-website/app/docs/v2/