export * from "./FrontendTabs";
export * from "./BackendTabs";
export * from "./RepositoryTabs";
export * from "./SelfHostingTabs";
export * from "./FrontendCustomUITabs";
export * from "./FrontendPrebuiltUITabs";
export * from "./ReactRouterVersionsTabs";
export * from "./DatabaseTabs";
export * from "./OSTabs";
