/**
 * Copyright (c) 2017-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

const React = require("react");

const CompLibrary = require("../../core/CompLibrary");

const Container = CompLibrary.Container;

const versions = {
  "v2": [
    "7.2.X",
    "7.1.X",
    "7.0.X",
    "6.1.X",
    "6.0.X"
  ],
  "v1": [
    "5.1.X",
    "5.0.X",
    "4.4.X",
    "4.3.X",
    "4.2.X",
    "4.1.X",
    "4.0.X",
    "3.4.X",
    "3.3.X",
    "3.2.X",
    "3.1.X",
    "3.0.X",
    "2.5.X",
    "2.4.X",
    "2.3.X",
    "2.2.X",
    "2.1.X",
    "2.0.X",
    "1.0.X",
    "0.0.X"
  ]
};

function Versions (props) {
  const { config: siteConfig } = props;
  return (
    <div className="docMainWrapper wrapper">
      <Container className="mainContainer versionsContainer">
        <div className="post">
          <header className="postHeader">
            <h1>{siteConfig.title} Versions</h1>
          </header>
          <table className="versions">
            <tbody id="sdk-autogenerated-docs-version-list"></tbody>
            <tbody>
              {[...versions.v2, ...versions.v1].map(
                version => (
                  <tr>
                    <th>{version}</th>
                    <td>
                      <a
                        href={`${siteConfig.baseUrl}${siteConfig.docsUrl}/${props.language ? props.language + "/" : ""
                          }${version}/installation`}>
                        Documentation
                      </a>
                    </td>
                  </tr>
                ),
              )}
            </tbody>
          </table>
        </div>
      </Container>
    </div>
  );
}

module.exports = Versions;
