#!/bin/bash

RED='\033[0;31m'
NC='\033[0m' # No color
YELLOW='\033[33m'
GREEN='\033[32m'
BLUE='\033[34m'

echo -e "${YELLOW}Compiles?${NC}"
cd v2/src/components
npx tsc -p tsconfig.json

doesBuild=$?

rm -rf build/

cd ../..
if [ $doesBuild -eq 0 ]
then
    echo -e "${GREEN}Yes${NC}\n"
else
    echo -e "${RED}No${NC}\n"
    echo -e "${RED}Cancelling commit because of build error.${NC}\n"
    exit 1
fi
