#!/bin/bash

echo "" # Adds a break line to the start for aesthetic

RED='\033[0;31m'
NC='\033[0m' # No color
YELLOW='\033[33m'
GREEN='\033[32m'
BLUE='\033[34m'

# If no arguments are passed exit
if [ $# -eq 0 ]
    then
    echo -e "${RED}No arguments passed, please provide a version number.\n${YELLOW}EXAMPLE USAGE: ./createVersion 1.0.X${NC}\n"
    exit 1
fi

versionNumber=$1
currentDir=$(pwd)
docsName=$(awk -F/ '{print $(NF-1)}' <<< $currentDir)

npm run version $versionNumber

echo -e "${YELLOW}Visit ${BLUE}https://docusaurus.io/docs/en/versioning${YELLOW} to understand how versioning works.${NC}"
echo "" # Adds a break line to the start for aesthetic
echo -e "${GREEN}The following have been created\n"
echo -e "- $docsName/website/versioned_docs/version-$versionNumber"
echo -e "- $docsName/website/versioned_sidebars/version-$versionNumber-sidebars.json"
echo -e "- $docsName/website/versions.json OR added an entry for $versionNumber in versions.json"
echo -e "${NC}" # Adds a break line to the start for aesthetic and resets color

echo -e "${YELLOW}To delete this version do the following -"
echo "" # Adds a break line to the start for aesthetic
echo -e "- ${RED}DELETE${YELLOW} $docsName/website/versioned_docs/version-$versionNumber"
echo -e "- ${RED}DELETE${YELLOW} $docsName/website/versioned_sidebars/version-$versionNumber-sidebars.json"
echo -e "- ${RED}REMOVE${YELLOW} $versionNumber from $docsName/website/versions.json"
echo -e "${BLUE}NOTE: ${YELLOW}if this version is the only version you have you should ${RED}DELETE${YELLOW} the ${BLUE}versioned_docs${YELLOW} and ${BLUE}versioned_sidebars${YELLOW} directories, ${RED}DELETE${YELLOW} ${BLUE}versions.json${YELLOW} and ${RED}DELETE${YELLOW} the ${BLUE}versions.js${YELLOW} file inside pages/en"
echo -e "${NC}" # Adds a break line to the start for aesthetic and resets color