#!/bin/bash

echo "" # Adds a break line to the start for aesthetic

file=siteConfig.js
RED='\033[0;31m'
NC='\033[0m' # No color
YELLOW='\033[33m'
GREEN='\033[32m'
BLUE='\033[34m'

if [ ! -f "$file" ]; then
    echo -e "${RED}Could not locate siteConfig.js in current directory, make sure you are running this command from inside the website folder of your documentation${NC}\n"
    exit 1
fi

npm run examples versions

currentDir=$(pwd)
docsName=$(awk -F/ '{print $(NF-1)}' <<< $currentDir)

echo -e "${GREEN}Succesfully initialised versions for $docsName.${NC}\n${YELLOW}This should have created a ${BLUE}versions.js${YELLOW} file in $docsName/website/pages/en${NC}"

echo "" # Adds a break line to the start for aesthetic

echo -e "${GREEN}Things to do next${YELLOW}"
echo "" # Adds a break line to the start for aesthetic
echo -e "- replace the contents of $docsName/website/pages/en/versions.js with the contents in $docsName/defaults/versions.js"
echo -e "${BLUE}NOTE: if you do not have a defaults directory or you have deleted it, you can use initialDocumentationSetup/defaults${YELLOW}"
echo -e "- visit ${BLUE}https://docusaurus.io/docs/en/versioning${YELLOW} to understand how versioning works in docusaurus"
echo -e "- Remember that after you create a version, changes to markdown files will not reflect in the current version. You will have to create a new version for those changes (or delete and re create the current version)"
echo -e "${NC}" # Adds a break line to the start for aesthetic and resets color