# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'iosenv' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosenv
  pod "SuperTokensIOS", "~> 0.2.5"
  pod 'xcbeautify'
  pod 'Alamofire'
  pod 'GoogleSignIn'

end
