# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'iosenv' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosenv
  pod "SuperTokensIOS", "~> 0.2.5"
  pod 'xcbeautify'
  pod 'Alamofire'
  pod 'GoogleSignIn'
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "14.0"
      end
    end
  end

end
